version: 1.0.{build}
environment:
  COVERALLS_REPO_TOKEN:
    secure: EzPyu+0iuuzRfWoTjni5ZMeBN0QUwme8+OPCu4X37If0x0zOuud1c5b2Sd3Z3cFZ
branches:
  only:
  - master
before_build:
- ps: nuget restore Drummers.sln
build:
  project: Drummers.sln
  verbosity: minimal

after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single src\Tests\UnitTests\Core\Drummers.Domain.Entities.Tests\bin\Debug\Drummers.Domain.Entities.Tests.dll" -filter:"+[*]*" -register:user  -output:coverage.xml
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
