version: 1.0.{build}
branches:
  only:
  - master
before_build:
- ps: nuget restore Drummers.sln
build:
  project: Drummers.sln
  verbosity: minimal

after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/nologo /noshadow test\Drummers.Services.Tests\bin\Debug\Drummers.Services.Tests.dll" -filter:"+[*]* -[*.Tests]*" -register:user
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover -i .coverage.xml
